-- Soap Notes: order-capture and email-signup schema.
-- Run this once in the Supabase SQL editor for a fresh project.
--
-- Design: the app only ever uses the anon key, from server-side Route
-- Handlers. Row-level security grants that key INSERT only — no SELECT,
-- UPDATE, or DELETE — so a leaked anon key (they're public by design) can
-- never read back an email address or an order, only add new ones. IDs are
-- generated by the app (crypto.randomUUID()) and passed in explicitly, so
-- the app never needs `RETURNING`, which would otherwise require a SELECT
-- policy too.

create table if not exists subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id uuid primary key,
  email text not null,
  total_cents integer not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders (id) on delete cascade,
  sku text not null,
  name text not null,
  unit_price_cents integer not null,
  quantity integer not null check (quantity > 0)
);

alter table subscribers enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

create policy "anon can insert subscribers" on subscribers
  for insert to anon
  with check (true);

create policy "anon can insert orders" on orders
  for insert to anon
  with check (true);

create policy "anon can insert order_items" on order_items
  for insert to anon
  with check (true);
